# Site Settings
title: Alex Tedeschi
url: "http://AlexTedeschi.github.io"
baseurl: "/" #change it according to your repository name
resume: True # Whether to display printable resume in sidebar.
activities: False # Whether to show activities.

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6
style: styles-fsu
#style: styles-salesforce

#Profile information
name: Alex Tedeschi
tagline: Computer Science Graduate from Florida State University
pic: headshot.jpg #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "An Enthusiastic Software Developer, IT Analyst, and System Administrator Apprentice with a driven work ethic."

#sidebar links
email: alextedeschi27@gmail.com
phone: (401) 484-2910
#blog: blog.cgsphoto.com #do not add http://
linkedin: AlexanderJTedeschi
github: AlexTedeschi
twitter: "alext227"
#photos: photos.cgsphoto.com
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: True

# Tracker
#analytics: UA-93997218-2

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
