# Site Settings
title: Carlos Saucedo
url: 'http://leosaucedo.github.io'
baseurl: '/' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Carlos Saucedo
tagline: Computer Science Student
pic: avatar.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Driven Computer Science Major at a highly competitive university, with extensive leadership, graphic design, 
and STEM expertise seeking to expand my experience as a Computer Scientist and programmer.'

#sidebar links
email: carlos@cgsphoto.com
phone: (561) 320-3150
website: photos.cgsphoto.com #do not add http://
#linkedin: CarlosSaucedo
github: LeoSaucedo
twitter: '@ThatLeoKid42'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
